type AnyHTMLElement = HTMLElement
  & HTMLAnchorElement
  & HTMLAreaElement
  & HTMLAudioElement
  & HTMLBaseElement
  & HTMLQuoteElement
  & HTMLBodyElement
  & HTMLBRElement
  & HTMLButtonElement
  & HTMLCanvasElement
  & HTMLTableCaptionElement
  & HTMLTableColElement
  & HTMLDataElement
  & HTMLDataListElement
  & HTMLModElement
  & HTMLDetailsElement
  & HTMLDialogElement
  & HTMLDivElement
  & HTMLDListElement
  & HTMLEmbedElement
  & HTMLFieldSetElement
  & HTMLFormElement
  & HTMLHeadingElement
  & HTMLHeadElement
  & HTMLHRElement
  & HTMLHtmlElement
  & HTMLIFrameElement
  & HTMLImageElement
  & HTMLInputElement
  & HTMLLabelElement
  & HTMLLegendElement
  & HTMLLIElement
  & HTMLLinkElement
  & HTMLMapElement
  & HTMLMenuElement
  & HTMLMetaElement
  & HTMLMeterElement
  & HTMLObjectElement
  & HTMLOListElement
  & HTMLOptGroupElement
  & HTMLOptionElement
  & HTMLOutputElement
  & HTMLParagraphElement
  & HTMLPictureElement
  & HTMLPreElement
  & HTMLProgressElement
  & HTMLScriptElement
  & HTMLSelectElement
  & HTMLSlotElement
  & HTMLSourceElement
  & HTMLSpanElement
  & HTMLStyleElement
  & HTMLTableElement
  & HTMLTableSectionElement
  & HTMLTableCellElement
  & HTMLTemplateElement
  & HTMLTextAreaElement
  & HTMLTimeElement
  & HTMLTitleElement
  & HTMLTableRowElement
  & HTMLTrackElement
  & HTMLUListElement
  & HTMLVideoElement